

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app
      - telegram_bot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $!; certbot renew; done;'"

  flask_app:
    build:
      context: ./flask_app
    container_name: flask_app
    expose:
      - "5000"
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: datanum
      SQLALCHEMY_DATABASE_URI: postgresql://flask_user:yourpassword@db:5432/datanum
    depends_on:
      - db
    restart: always

  telegram_bot:
    build:
      context: ./bot_app
    container_name: telegram_bot
    env_file: 
      - .env  # Переменные окружения берём из файла .env
    expose:
      - "8080"
    restart: always

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: datanum
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
 